name: Deploy Deno
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - run: corepack enable
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      # Pick your own package manager and build script
      - run: pnpm install
      - run: NITRO_PRESET=deno-deploy pnpm run build
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "ailoveu-nuxt-cn-opt-52"
          entrypoint: "server/index.mjs"
          root: ".output"

          
          
